"""Load the pre-processed GRACE country-year groundwater anomaly panel.

Context: from raster to panel
-------------------------------
The raw GRACE data is a global gridded raster (a 2D map at each time step). Before
this module is called, a separate processing step — src/ingest/download/grace_process.py
— has already:
    1. Downloaded the NASA GRACE Mascon netCDF4 product.
    2. Aggregated pixel-level LWE anomaly values to country-level annual means using
       area-weighted spatial averaging (see grace.py for the spatial aggregation logic).
    3. Written the results to a compact CSV with one row per (country, year).

This module's job is simply to load that pre-processed CSV, validate it has the
expected structure, and return it as a pandas DataFrame ready for the Master Panel.

The pre-computed panel approach has two advantages:
    1. Speed: the spatial aggregation over a global raster for ~200 countries x 20 years
       is computationally expensive (~minutes). Pre-computing it once and saving as CSV
       means all downstream steps (pipeline, API, dashboard) are fast.
    2. Reproducibility: the CSV can be version-controlled (or hashed) separately from
       the raw netCDF4 files, which are large (hundreds of MB) and stored outside the
       repository.

Key variable
-------------
grace_lwe_anomaly_cm: The country-level mean Liquid Water Equivalent (LWE) anomaly
    in centimetres, relative to the 2004-2009 baseline. A value of -3.5 means that,
    on average across the country's land area, total terrestrial water storage is
    3.5 cm less than the long-term mean for that location — a signal of drought,
    aquifer depletion, or both. Positive values indicate more water than average
    (wetter year, recovering aquifer, or large snowpack).

    This variable feeds directly into:
    - H7 analysis (groundwater depletion → GDP trajectory): the depletion rate
      (slope of the anomaly time series) is the key predictor.
    - Phase 4 ML models: grace_lwe_anomaly_cm and its lag/rolling features are
      inputs to the instability and migration models.

Source: NASA GRACE Mascon product (JPL RL06)
Processing: src/ingest/download/grace_process.py
Full spatial aggregation: src/ingest/grace.py
"""

import pandas as pd

# All three columns must be present in the pre-processed CSV. Validated immediately
# after the file is read — any missing column triggers a fail-fast error rather than
# silently producing wrong output downstream. If the CSV is regenerated by
# grace_process.py and the schema changes, this check will catch it immediately.
_REQUIRED_COLUMNS = ["iso3", "year", "grace_lwe_anomaly_cm"]


def load_grace_panel(path) -> pd.DataFrame:
    """Load the pre-processed GRACE country-year groundwater anomaly panel from CSV.

    This is the lightweight loader for the panel that was produced by the GRACE
    spatial aggregation pipeline. It validates the file structure and ensures the
    year column is stored as an integer (consistent with all other GFIP data sources).

    No country name translation is needed here — the pre-processing step has already
    converted country names to ISO3 codes, and the CSV stores them directly.

    No pivoting or reshaping is needed — the CSV is already in the tidy
    (one row per country-year) format that the Master Panel assembler expects.

    Args:
        path: File path (str or pathlib.Path) to the pre-processed GRACE CSV, or any
            file-like object (e.g. io.StringIO) that pandas can read. Accepting
            file-like objects allows tests to pass in-memory CSV strings without
            touching the filesystem.

    Returns:
        A tidy pandas DataFrame with one row per (iso3, year) combination and columns:
        - iso3 (str): ISO 3166-1 alpha-3 country code.
        - year (int64): Calendar year (2002-present, with a gap around 2017-2018
          between the GRACE and GRACE-FO missions).
        - grace_lwe_anomaly_cm (float): Country-level area-weighted mean LWE anomaly
          in centimetres relative to the 2004-2009 baseline. Negative = depletion.
          A depletion rate of -0.5 cm/year means groundwater is decreasing at
          0.5 cm water equivalent per year on average across the country's land area.
          NaN is expected for country-years where GRACE data is absent (e.g. the
          inter-mission gap, or island states too small to resolve on the grid).

    Raises:
        ValueError: If any of _REQUIRED_COLUMNS are absent from the CSV.
            Message: "Missing required columns: [<list of missing column names>]"
    """
    df = pd.read_csv(path)

    # Validate required columns immediately — fail-fast rather than producing
    # confusing KeyError or NaN-filled output further down the pipeline.
    missing = [c for c in _REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    # Ensure year is stored as int64 for consistent joins with other GFIP panels.
    # CSV files often read numeric columns as float64 if any values are missing
    # (pandas converts int columns to float when NaN is present). Casting here
    # guarantees the merge key type matches across all ingest modules.
    df["year"] = df["year"].astype("int64")
    return df
