/**
 * Panel 2 — Outcomes Explorer
 *
 * This panel visualises the Phase 3 hypothesis testing results. For each of the
 * seven GFIP hypotheses (H1–H7), it shows the regression effect size (beta
 * coefficient) and the statistical confidence in that result (p-value). A
 * confirmed hypothesis (p < 0.05, correct sign) appears with a green left border;
 * a directionally consistent but not yet significant result appears in amber.
 *
 * WHAT THE NUMBERS MEAN
 * The key number on this panel is beta (β) — the regression coefficient. It tells
 * you HOW MUCH the outcome changes per unit improvement in the freshwater exposure,
 * holding constant everything permanently different between countries (geography,
 * history, culture) and everything that changed globally in any given year (global
 * economic cycles, technology, pandemics). This "two-way fixed effects" design is
 * the gold standard for causal inference in cross-country panel data.
 *
 * p-value: the probability of observing an effect this large by chance alone if the
 * true effect were zero. Values below 0.05 are the conventional threshold for
 * "statistically significant". However, even directional results (correct sign,
 * p > 0.05) are informative — they tell us the data is consistent with the theory,
 * just not yet definitive at the current sample size.
 *
 * n_obs: the number of country-year observations used in this regression. Larger
 * samples give more power to detect small effects. Our panel covers up to ~5,000
 * country-years for well-reported variables.
 *
 * What this tells a policymaker:
 *   - The direction of the effect (does more water = more income, or less conflict?)
 *   - The magnitude (a unit drop in water → X fewer years of life expectancy)
 *   - The confidence level (do we have enough data to be sure?)
 *
 * Plain-language interpretation is generated by the `interpret()` function and
 * displayed below each result card, so readers without statistics training can
 * understand the findings without reading a regression table.
 *
 * The scatter plots showing H1–H7 pairwise relationships are planned for Phase 5
 * iteration 2 using Recharts.
 */

import { useEffect, useState } from "react";
import { api } from "../api/client";
import type { HypothesisResult } from "../api/client";

/**
 * Generate a plain-language interpretation of one hypothesis result.
 *
 * Translates the statistical output (beta, p-value, n) into a sentence that a
 * non-statistician can read. The direction word ("increases" / "decreases") is
 * derived from the sign of beta. The significance label distinguishes confirmed
 * results (p < 0.05) from directionally consistent but uncertain ones.
 *
 * This function is intentionally verbose — the goal is accessibility for
 * policymakers and journalists, not brevity.
 *
 * @param h - A single HypothesisResult from the /api/v1/hypotheses endpoint.
 * @returns A plain-English sentence summarising the finding.
 */
const interpret = (h: HypothesisResult): string => {
  const dir = h.beta > 0 ? "increases" : "decreases";
  const sig = h.p_value < 0.05 ? "statistically significant" : "directionally consistent but not yet statistically significant";
  return `A unit improvement in ${h.exposure} ${dir} ${h.outcome} by ${Math.abs(h.beta).toFixed(3)} units. This result is ${sig} (p = ${h.p_value.toFixed(3)}, n = ${h.n_obs.toLocaleString()} country-years).`;
};

/**
 * OutcomesExplorer component — renders the H1–H7 hypothesis testing results panel.
 *
 * Fetches results from GET /api/v1/hypotheses on mount (results are hardcoded in
 * the API from the Phase 3 R analysis — they do not change at runtime). Renders one
 * card per hypothesis, with a colour-coded left border (green = confirmed, amber =
 * directional) and a plain-language interpretation below the statistical numbers.
 */
export default function OutcomesExplorer() {
  const [hypotheses, setHypotheses] = useState<HypothesisResult[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.hypotheses().then(setHypotheses).finally(() => setLoading(false));
  }, []);

  if (loading) return <p>Loading hypothesis results…</p>;

  return (
    <div style={{ maxWidth: 900 }}>
      <h2>Outcomes Explorer — Does Water Drive Human Welfare?</h2>
      <p style={{ color: "#555" }}>
        These results come from two-way fixed effects panel regression — a statistical
        method that controls for everything permanently different between countries
        (geography, history, culture) and asks only: <em>within the same country,
        when water availability changed, did human outcomes change?</em>
        This is the gold standard for establishing causal relationships in
        cross-country panel data.
      </p>

      <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
        {hypotheses.map(h => (
          <div key={h.id} style={{ border: "1px solid #ddd", borderRadius: 8, padding: 16,
            // Visual encoding: the left border colour signals the result status at a glance.
            // Green = statistically confirmed (p < 0.05, correct sign).
            // Amber = directionally consistent — the effect is in the right direction,
            // but the sample size or data quality doesn't yet meet the p < 0.05 threshold.
            borderLeft: `4px solid ${h.confirmed ? "#2e7d32" : "#e65100"}` }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
              <span style={{ fontWeight: 700, fontSize: 18, color: "#1a3a5c" }}>{h.id}</span>
              <span style={{ fontWeight: 500 }}>{h.label}</span>
              <span style={{ marginLeft: "auto", background: h.confirmed ? "#e8f5e9" : "#fff3e0",
                color: h.confirmed ? "#2e7d32" : "#e65100", borderRadius: 4, padding: "2px 10px", fontSize: 12 }}>
                {h.confirmed ? "Confirmed" : "Directional"}
              </span>
            </div>
            {/* β (beta) is the key number — it tells you HOW MUCH the outcome changes
                per unit of exposure, not just whether a relationship exists. A policy
                reader can use this to estimate the real-world impact of a 10% improvement
                in freshwater availability on e.g. GDP or life expectancy. */}
            <div style={{ display: "flex", gap: 24, marginBottom: 8, fontSize: 14, color: "#555" }}>
              <span><strong>β</strong> = {h.beta.toFixed(3)}</span>
              <span><strong>p</strong> = {h.p_value.toFixed(4)}</span>
              <span><strong>n</strong> = {h.n_obs.toLocaleString()}</span>
            </div>
            <p style={{ margin: 0, fontSize: 14, color: "#333" }}>{interpret(h)}</p>
            {h.note && <p style={{ margin: "8px 0 0", fontSize: 12, color: "#888", fontStyle: "italic" }}>{h.note}</p>}
          </div>
        ))}
      </div>
    </div>
  );
}
